export const STATES = {
    alabama: "alabama",
    alaska: "alaska",
    arizona: "arizona",
    arkansas: "arkansas",
    california: "california",
    colorado: "colorado",
    connecticut: "connecticut",
    delaware: "delaware",
    florida: "florida",
    georgia: "georgia",
    hawaii: "hawaii",
    idaho: "idaho",
    illinois: "illinois",
    indiana: "indiana",
    iowa: "iowa",
    kansas: "kansas",
    kentucky: "kentucky",
    louisiana: "louisiana",
    maine: "maine",
    maryland: "maryland",
    massachusetts: "massachusetts",
    michigan: "michigan",
    minnesota: "minnesota",
    mississippi: "mississippi",
    missouri: "missouri",
    montana: "montana",
    nebraska: "nebraska",
    nevada: "nevada",
    newhampshire: "new hampshire",
    newjersey: "new jersey",
    newmexico: "new mexico",
    newyork: "new york",
    northcarolina: "north carolina",
    northdakota: "north dakota",
    ohio: "ohio",
    oklahoma: "oklahoma",
    oregon: "oregon",
    pennsylvania: "pennsylvania",
    rhodeisland: "rhode island",
    southcarolina: "south carolina",
    southdakota: "south dakota",
    tennessee: "tennessee",
    texas: "texas",
    utah: "utah",
    vermont: "vermont",
    virginia: "virginia",
    washington: "washington",
    westvirginia: "west virginia",
    wisconsin: "wisconsin",
    wyoming: "wyoming",
};


export const EXTRA = {
    alberta: 'alberta',
    britishcolumbia: 'british columbia',
    manitoba: 'manitoba',
    newbrunswick: 'new brunswick',
    newfoundland: 'newfoundland',
    novascotia: 'nova scotia',
    ontario: 'ontario',
    princeedwardisland: 'prince edward island',
    quebec: 'quebec',
    saskatchewan: 'saskatchewan',
    yukon: 'yukon',
    northwestterritory: 'north west territory',
    nunavut: 'nunavut',
}